Masters = {
	["赵灵珠"] = {
		id = "zhao lingzhu",
		addr = {name = "莲花石", city = "峨嵋山"},
		skills = {
			blade = {id = "blade",level = 80,name = "基本刀法",},
			["huifeng-jian"] = {id = "huifeng-jian",level = 80,name = "huifeng-jian",},
			sword = {id = "sword",level = 80,name = "基本剑法",},
			["linji-zhuang"] = {id = "linji-zhuang",level = 80,name = "临济十二庄",},
			parry = {id = "parry",level = 90,name = "基本招架",},
			defaultvalue = {practice = 0,level = 0,},["yanxing-daofa"] = {id = "yanxing-daofa",level = 80,name = "雁行刀法",},
			dodge = {id = "dodge",level = 90,name = "基本轻功",},
			literate = {id = "literate",level = 90,name = "读书写字",},
			force = {id = "force",level = 90,name = "基本内功",},
			["dacheng-fofa"] = {id = "dacheng-fofa",level = 90,name = "大乘佛法",},
			["anying-fuxiang"] = {id = "anying-fuxiang",level = 90,name = "暗影浮香",}
		},
	},
	["采矿师傅"] = {
		id = "caikuang shifu",
		addr = {name = "city/dongdajie0"},
		move = true,
		skills = {
			caikuang = {id = "caikuang", level = 50, name = "采矿技能",},
		},
	},
	["养蚕婆婆"] = {
		id = "yangcan popo",
		addr = {name = "changan/northjie2"},
		move = true,
		skills = {
			nongsang = {id = "nongsang", level = 50, name = "农桑技能",},
		},
	},
	["老裁缝"] = {
		id = "lao caifeng",
		addr = {name = "zhiye/caifengpu1"},
		skills = {
			zhizao = {id = "zhizao", level = 221, name = "织造术",},
		},
	},
	["铸剑师"] = {
		id = "zhujian shi",
		addr = {name = "zhiye/bingqipu1"},
		skills = {
			duanzao = {id = "duanzao", level = 221, name = "锻造技能",},
		},
	},
	["薛慕华"] = {
		id = "xue muhua",
		addr = {name = "正厅", city = "柳宗镇"},
		skills = {
			strike = {id = "strike",level = 229,name = "基本掌法",},
			["jingmai-xue"] = {id = "jingmai-xue",level = 180,name = "经脉学",},
			art = {id = "art",level = 180,name = "art",},
			["lingbo-weibu"] = {id = "lingbo-weibu",level = 229,name = "凌波微步",},
			medicine = {id = "medicine",level = 180,name = "本草术理",},
			parry = {id = "parry",level = 229,name = "基本招架",},
			dodge = {id = "dodge",level = 229,name = "基本轻功",},
			literate = {id = "literate",level = 240,name = "读书写字",},
			force = {id = "force",level = 229,name = "基本内功",},
			hand = {id = "hand",level = 229,name = "基本手法",},
		}
	},
	["高则成"] = {
		id = "gao zecheng",
		addr = {name = "广场", city = "昆仑山"}
	},
	["何太冲"] = {
		id = "he taichong",
		addr = {name = "铁琴居", city = "昆仑山"},
		skills = {
			cuff = {id = "cuff",level = 180,name = "基本拳法",},
			["zhentian-quan"] = {id = "zhentian-quan",level = 180,name = "震天拳",},
			["taxue-wuhen"] = {id = "taxue-wuhen",level = 190,name = "踏雪无痕",},
			sword = {id = "sword",level = 200,name = "基本剑法",},
			["xunlei-jian"] = {id = "xunlei-jian",level = 195,name = "迅雷十六剑",},
			parry = {id = "parry",level = 195,name = "基本招架",},
			force = {id = "force",level = 200,name = "基本内功",},
			dodge = {id = "dodge",level = 190,name = "基本轻功",},
			literate = {id = "literate",level = 140,name = "读书写字",},
			["mantian-huayu"] = {id = "mantian-huayu",level = 195,name = "漫天花雨",},
			throwing = {id = "throwing",level = 180,name = "基本暗器",},
			["xuantian-wuji"] = {id = "xuantian-wuji",level = 200,name = "玄天无极功",},
		},
	},
	["何足道"] = {
		id = "he zudao",
		short = "he",
		addr = {name = "惊神峰", city = "昆仑山"},
		skills = {
			strike = {id = "strike",level = 350,name = "基本掌法",},
			throwing = {id = "throwing",level = 300,name = "基本暗器",},
			["taxue-wuhen"] = {id = "taxue-wuhen",level = 360,name = "踏雪无痕",},
			art = {id = "art",level = 200,name = "琴棋书画",},
			["xunlei-jian"] = {id = "xunlei-jian",level = 200,name = "迅雷十六剑",},
			parry = {id = "parry",level = 360,name = "基本招架",},
			dodge = {id = "dodge",level = 360,name = "基本轻功",},
			sword = {id = "sword",level = 380,name = "基本剑法",},
			["liangyi-jian"] = {id = "liangyi-jian",level = 380,name = "两仪剑法",},
			["kunlun-zhang"] = {id = "kunlun-zhang",level = 350,name = "昆仑掌法",},
			force = {id = "force",level = 380,name = "基本内功",},
			literate = {id = "literate",level = 250,name = "读书写字",},
			["xuantian-wuji"] = {id = "xuantian-wuji",level = 380,name = "玄天无极功",},
		},
	},
	["班淑娴"] = {
		id = "ban shuxian",
		addr = {name = "三圣堂", city = "昆仑山"},
		skills = {
			leg = {id = "leg",level = 160,name = "基本腿法",},
			["taxue-wuhen"] = {id = "taxue-wuhen",level = 175,name = "踏雪无痕",},
			sword = {id = "sword",level = 190,name = "基本剑法",},
			["xunlei-jian"] = {id = "xunlei-jian",level = 180,name = "迅雷十六剑",},
			parry = {id = "parry",level = 180,name = "基本招架",},
			force = {id = "force",level = 175,name = "基本内功",},
			throwing = {id = "throwing",level = 185,name = "基本暗器",},
			dodge = {id = "dodge",level = 165,name = "基本轻功",},
			["chuanyun-tui"] = {id = "chuanyun-tui",level = 180,name = "穿云腿",},
			["mantian-huayu"] = {id = "mantian-huayu",level = 180,name = "漫天花雨",},
			literate = {id = "literate",level = 120,name = "读书写字",},
			["xuantian-wuji"] = {id = "xuantian-wuji",level = 180,name = "玄天无极功",},
		},
	},
	["宋远桥"] = {
		id = "song yuanqiao",
		addr = {name = "三清殿", city = "武当山"}
	},
	["清善比丘"] = {
		id = "qingshan biqiu",
		addr = {name = "前殿", city = "少林寺"},
		skills = {
			strike = {id = "strike",level = 35,name = "基本掌法",},
			parry = {id = "parry",level = 30,name = "基本招架",},
			["weituo-zhang"] = {id = "weituo-zhang",level = 35,name = "韦陀掌",},
			["yijin-jing"] = {id = "yijin-jing",level = 30,name = "易筋经",},
			dodge = {id = "dodge",level = 30,name = "基本轻功",},
			literate = {id = "literate",level = 30,name = "读书写字",},
			force = {id = "force",level = 30,name = "基本内功",},
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 30,name = "少林身法",},
			buddhism = {id = "buddhism",level = 30,name = "禅宗心法",},
		},
	},
	["道正禅师"] = {
		id = "daozheng chanshi",
		addr = {name = "大悲殿", city = "少林寺"},
		skills = {
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 50,name = "少林身法",},
			cuff = {id = "cuff",level = 55,name = "基本拳法",},
			buddhism = {id = "buddhism",level = 50,name = "禅宗心法",},
			sword = {id = "sword",level = 50,name = "基本剑法",},
			["yijin-jing"] = {id = "yijin-jing",level = 50,name = "易筋经",},
			parry = {id = "parry",level = 50,name = "基本招架",},
			["weituo-zhang"] = {id = "weituo-zhang",level = 50,name = "韦陀掌",},
			strike = {id = "strike",level = 50,name = "基本掌法",},
			["damo-jian"] = {id = "damo-jian",level = 50,name = "达摩剑",},
			dodge = {id = "dodge",level = 50,name = "基本轻功",},
			literate = {id = "literate",level = 50,name = "读书写字",},
			force = {id = "force",level = 50,name = "基本内功",},
			["luohan-quan"] = {id = "luohan-quan",level = 55,name = "罗汉拳",},
		},
	},
	["慧名尊者"] = {
		id = "huiming zunzhe",
		addr = {name = "shaolin/sblu-1"},
		skills = {
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 70,name = "少林身法",},
			["yijin-jing"] = {id = "yijin-jing",level = 70,name = "易筋经",},
			parry = {id = "parry",level = 70,name = "基本招架",},
			["weituo-zhang"] = {id = "weituo-zhang",level = 74,name = "韦陀掌",},
			["xiuluo-dao"] = {id = "xiuluo-dao",level = 70,name = "修罗刀",},
			strike = {id = "strike",level = 74,name = "基本掌法",},
			dodge = {id = "dodge",level = 70,name = "基本轻功",},
			literate = {id = "literate",level = 70,name = "读书写字",},
			force = {id = "force",level = 70,name = "基本内功",},
			blade = {id = "blade",level = 70,name = "基本刀法",},
			buddhism = {id = "buddhism",level = 70,name = "禅宗心法",},
		},
	},
	["澄思"] = {
		id = "chengsi luohan",
		addr = {name = "般若堂三部"},
		skills = {
			strike = {id = "strike",level = 100,name = "基本掌法",},
			parry = {id = "parry",level = 100,name = "基本招架",},
			["weituo-zhang"] = {id = "weituo-zhang",level = 81,name = "韦陀掌",},
			["yijin-jing"] = {id = "yijin-jing",level = 100,name = "易筋经",},
			dodge = {id = "dodge",level = 100,name = "基本轻功",},
			literate = {id = "literate",level = 100,name = "读书写字",},
			force = {id = "force",level = 100,name = "基本内功",},
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 100,name = "少林身法",},
			buddhism = {id = "buddhism",level = 100,name = "禅宗心法",},
		},
	},
	["玄慈大师"] = {
		id = "xuanci dashi",
		short = "xuanci",
		addr = {name = "方丈室", city = "少林寺"},
		skills = {
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 160,name = "少林身法",},
			["yijin-jing"] = {id = "yijin-jing",level = 160,name = "易筋经",},
			strike = {id = "strike",level = 160,name = "基本掌法",},
			buddhism = {id = "buddhism",level = 160,name = "禅宗心法",},
			["fengyun-shou"] = {id = "fengyun-shou",level = 160,name = "风云手",},
			["sanhua-zhang"] = {id = "sanhua-zhang",level = 160,name = "散花掌",},
			parry = {id = "parry",level = 160,name = "基本招架",},
			["nianhua-zhi"] = {id = "nianhua-zhi",level = 160,name = "拈花指",},
			force = {id = "force",level = 160,name = "基本内功",},
			finger = {id = "finger",level = 160,name = "基本指法",},
			["longzhua-gong"] = {id = "longzhua-gong",level = 160,name = "龙爪功",},
			dodge = {id = "dodge",level = 160,name = "基本轻功",},
			literate = {id = "literate",level = 160,name = "读书写字",},
			claw = {id = "claw",level = 160,name = "基本爪法",},
			hand = {id = "hand",level = 160,name = "基本手法",},
		},
	},
	["方生大师"] = {
		id = "fangsheng dashi",
		short = "fangsheng",
		addr = {name = "心禅堂"},
		skills = {
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 180,name = "少林身法",},
			cuff = {id = "cuff",level = 180,name = "基本拳法",},
			buddhism = {id = "buddhism",level = 180,name = "禅宗心法",},
			["yijin-jing"] = {id = "yijin-jing",level = 180,name = "易筋经",},
			["ruying-suixingtui"] = {id = "ruying-suixingtui",level = 180,name = "如影随形腿",},
			strike = {id = "strike",level = 180,name = "基本掌法",},
			parry = {id = "parry",level = 180,name = "基本招架",},
			literate = {id = "literate",level = 150,name = "读书写字",},
			leg = {id = "leg",level = 180,name = "基本腿法",},
			["jingang-quan"] = {id = "jingang-quan",level = 180,name = "大金刚拳",},
			dodge = {id = "dodge",level = 180,name = "基本轻功",},
			["banruo-zhang"] = {id = "banruo-zhang",level = 180,name = "般若掌",},
			force = {id = "force",level = 180,name = "基本内功",},
			finger = {id = "finger",level = 180,name = "基本指法",},
			["yizhi-chan"] = {id = "yizhi-chan",level = 180,name = "一指禅",},
		},
	},
	["无名老僧"] = {
		id = "wuming laoseng",
		short = "laoseng",
		addr = {name = "里屋", city = "少林寺"},
		skills = {
			cuff = {id = "cuff",level = 400,name = "基本拳法",},
			finger = {id = "finger",level = 400,name = "基本指法",},
			["ruying-suixingtui"] = {id = "ruying-suixingtui",level = 400,name = "如影随形腿",},
			["zui-gun"] = {id = "zui-gun",level = 400,name = "少林醉棍",},
			["xiuluo-dao"] = {id = "xiuluo-dao",level = 400,name = "修罗刀",},
			["yijin-jing"] = {id = "yijin-jing",level = 400,name = "易筋经",},
			club = {id = "club",level = 400,name = "基本棍法",},
			["longzhua-gong"] = {id = "longzhua-gong",level = 400,name = "龙爪功",},
			dodge = {id = "dodge",level = 400,name = "基本轻功",},
			literate = {id = "literate",level = 250,name = "读书写字",},
			force = {id = "force",level = 400,name = "基本内功",},
			hand = {id = "hand",level = 400,name = "基本手法",},
			["yizhi-chan"] = {id = "yizhi-chan",level = 400,name = "一指禅",},
			blade = {id = "blade",level = 400,name = "基本刀法",},
			["fumoquan-zhen"] = {id = "fumoquan-zhen",level = 200,name = "伏魔圈阵",},
			leg = {id = "leg",level = 400,name = "基本腿法",},
			buddhism = {id = "buddhism",level = 200,name = "禅宗心法",},
			["weituo-chu"] = {id = "weituo-chu",level = 400,name = "韦陀杵",},
			strike = {id = "strike",level = 400,name = "基本掌法",},
			["qianye-shou"] = {id = "qianye-shou",level = 400,name = "如来千叶手",},
			["nianhua-zhi"] = {id = "nianhua-zhi",level = 400,name = "拈花指",},
			["shaolin-shenfa"] = {id = "shaolin-shenfa",level = 400,name = "少林身法",},
			["riyue-bian"] = {id = "riyue-bian",level = 400,name = "riyue-bian",},
			["ranmu-daofa"] = {id = "ranmu-daofa",level = 400,name = "燃木刀法",},
			parry = {id = "parry",level = 400,name = "基本招架",},
			["banruo-zhang"] = {id = "banruo-zhang",level = 400,name = "般若掌",},
			claw = {id = "claw",level = 400,name = "基本爪法",},
			["jingang-quan"] = {id = "jingang-quan",level = 400,name = "大金刚拳",},
			whip = {id = "whip",level = 400,name = "基本鞭法",},
		},
	},
	["顾炎武"] = {
		id = "gu yanwu",
		addr = {name = "书院", city = "扬州城"},
		skills = {
			literate = {id = "literate",level = 300,name = "读书写字",},
		},
	},
	["王夫人"] = {
		id = "wang furen",
		addr = {name = "云锦楼",},
		skills = {
			strike = {id = "strike",level = 100,name = "基本掌法",},
			["murong-jianfa"] = {id = "murong-jianfa",level = 100,name = "murong-jianfa",},
			sword = {id = "sword",level = 100,name = "基本剑法",},
			["canhe-zhi"] = {id = "canhe-zhi",level = 100,name = "参合指",},
			["xingyi-zhang"] = {id = "xingyi-zhang",level = 100,name = "星移掌",},
			["yanling-shenfa"] = {id = "yanling-shenfa",level = 100,name = "燕灵身法",},
			["shenyuan-gong"] = {id = "shenyuan-gong",level = 100,name = "神元功",},
			dodge = {id = "dodge",level = 100,name = "基本轻功",},
			literate = {id = "literate",level = 100,name = "读书写字",},
			force = {id = "force",level = 100,name = "基本内功",},
			parry = {id = "parry",level = 100,name = "基本招架",},
			finger = {id = "finger",level = 100,name = "基本指法",},
		},
	},
	["公冶乾"] = {
		id = "gongye gan",
		addr = {name = "mr/yanziwu/dating",},
		skills = {
			strike = {id = "strike",level = 130,name = "基本掌法",},
			["murong-jianfa"] = {id = "murong-jianfa",level = 130,name = "慕容剑法",},
			finger = {id = "finger",level = 130,name = "基本指法",},
			sword = {id = "sword",level = 130,name = "基本剑法",},
			["canhe-zhi"] = {id = "canhe-zhi",level = 130,name = "参合指",},
			["yanling-shenfa"] = {id = "yanling-shenfa",level = 130,name = "燕灵身法",},
			["xingyi-zhang"] = {id = "xingyi-zhang",level = 130,name = "星移掌",},
			dodge = {id = "dodge",level = 130,name = "基本轻功",},
			literate = {id = "literate",level = 130,name = "读书写字",},
			force = {id = "force",level = 130,name = "基本内功",},
			["shenyuan-gong"] = {id = "shenyuan-gong",level = 130,name = "神元功",},
			parry = {id = "parry",level = 130,name = "基本招架",},
		},
	},
	["张无忌"] = {
		id = "zhang wuji",
		addr = {name = "圣火堂"},
		skills = {
			["shenghuo-shengong"] = {id = "shenghuo-shengong",level = 340,name = "圣火神功",},
			["lieyan-dao"] = {id = "lieyan-dao",level = 230,name = "烈焰刀",},
			cuff = {id = "cuff",level = 380,name = "基本拳法",},
			["qiankun-danuoyi"] = {id = "qiankun-danuoyi",level = 380,name = "乾坤大挪移",},
			sword = {id = "sword",level = 340,name = "基本剑法",},
			["shenghuo-lingfa"] = {id = "shenghuo-lingfa",level = 380,name = "圣火令法",},
			medicine = {id = "medicine",level = 190,name = "本草术理",},
			["jiuyang-shengong"] = {id = "jiuyang-shengong",level = 380,name = "九阳神功",},
			dodge = {id = "dodge",level = 350,name = "基本轻功",},
			literate = {id = "literate",level = 250,name = "读书写字",},
			force = {id = "force",level = 370,name = "基本内功",},
			hand = {id = "hand",level = 320,name = "基本手法",},
			blade = {id = "blade",level = 230,name = "基本刀法",},
			["qishang-quan"] = {id = "qishang-quan",level = 360,name = "七伤拳",},
			["yingzhua-shou"] = {id = "yingzhua-shou",level = 320,name = "鹰爪擒拿手",},
			tiyunzong = {id = "tiyunzong",level = 320,name = "梯云纵",},
			parry = {id = "parry",level = 380,name = "基本招架",},
			["taiji-quan"] = {id = "taiji-quan",level = 330,name = "太极拳",},
			["taiji-jian"] = {id = "taiji-jian",level = 320,name = "太极剑法",},
			strike = {id = "strike",level = 340,name = "基本掌法",},
			["shenghuo-fumozhen"] = {id = "shenghuo-fumozhen",level = 200,name = "圣火伏魔阵",},
			["piaoyi-shenfa"] = {id = "piaoyi-shenfa",level = 350,name = "飘翼身法",},
			dagger = {id = "dagger",level = 380,name = "基本匕法",},
			["hanbing-mianzhang"] = {id = "hanbing-mianzhang",level = 340,name = "寒冰绵掌",},
			["liehuo-jian"] = {id = "liehuo-jian",level = 230,name = "烈火剑",},
		},
	},
	["殷无福"] = {
		id = "yin wufu",
		addr = {name = "黄土坪", city = "明教"},
		skills = {
			["shenghuo-shengong"] = {id = "shenghuo-shengong",level = 90,name = "圣火神功",},
			["lieyan-dao"] = {id = "lieyan-dao",level = 90,name = "烈焰刀",},
			parry = {id = "parry",level = 90,name = "基本招架",},
			["piaoyi-shenfa"] = {id = "piaoyi-shenfa",level = 90,name = "飘翼身法",},
			dodge = {id = "dodge",level = 90,name = "基本轻功",},
			["yingzhua-shou"] = {id = "yingzhua-shou",level = 90,name = "鹰爪手",},
			force = {id = "force",level = 90,name = "基本内功",},
			hand = {id = "hand",level = 90,name = "基本手法",},
			blade = {id = "blade",level = 90,name = "基本刀法",},
		},
	},
	["殷野王"] = {
		id = "yin yewang",
		addr = {name = "总坛前厅", city = "明教"},
		skills = {
			blade = {id = "blade",level = 110,name = "基本刀法",},
			["lieyan-dao"] = {id = "lieyan-dao",level = 110,name = "烈焰刀",},
			sword = {id = "sword",level = 110,name = "基本剑法",},
			parry = {id = "parry",level = 110,name = "基本招架",},
			["piaoyi-shenfa"] = {id = "piaoyi-shenfa",level = 110,name = "飘翼身法",},
			["yingzhua-shou"] = {id = "yingzhua-shou",level = 110,name = "鹰爪手",},
			["shenghuo-shengong"] = {id = "shenghuo-shengong",level = 110,name = "圣火神功",},
			dodge = {id = "dodge",level = 110,name = "基本轻功",},
			literate = {id = "literate",level = 110,name = "读书写字",},
			force = {id = "force",level = 110,name = "基本内功",},
			hand = {id = "hand",level = 110,name = "基本手法",},
			["liehuo-jian"] = {id = "liehuo-jian",level = 110,name = "烈火剑",},
		}
	},
	["韦一笑"] = {
		id = "wei yixiao",
		addr = {name = "mingjiao/guangc"},
		skills = {
			["piaoyi-shenfa"] = {id = "piaoyi-shenfa",level = 190,name = "飘翼身法",},
			strike = {id = "strike",level = 180,name = "基本掌法",},
			["shenghuo-shengong"] = {id = "shenghuo-shengong",level = 140,name = "圣火神功",},
			dodge = {id = "dodge",level = 190,name = "基本轻功",},
			literate = {id = "literate",level = 110,name = "读书写字",},
			force = {id = "force",level = 150,name = "基本内功",},
			["hanbing-mianzhang"] = {id = "hanbing-mianzhang",level = 180,name = "寒冰绵掌",},
			parry = {id = "parry",level = 150,name = "基本招架",},
		},
	},
	["冷谦"] = {
		id = "leng qian",
		short = "leng",
		addr = {name = "监狱入口", city = "明教"},
		skills = {
			blade = {id = "blade",level = 125,name = "基本刀法",},
			["lieyan-dao"] = {id = "lieyan-dao",level = 125,name = "烈焰刀",},
			["jinshe-zhangfa"] = {id = "jinshe-zhangfa",level = 125,name = "金蛇游身掌",},
			parry = {id = "parry",level = 125,name = "基本招架",},
			["piaoyi-shenfa"] = {id = "piaoyi-shenfa",level = 125,name = "飘翼身法",},
			dodge = {id = "dodge",level = 125,name = "基本轻功",},
			literate = {id = "literate",level = 80,name = "读书写字",},
			force = {id = "force",level = 125,name = "基本内功",},
			strike = {id = "strike",level = 125,name = "基本掌法",},
			["shenghuo-shengong"] = {id = "shenghuo-shengong",level = 125,name = "圣火神功",},
		},
	},
	["陈长老"] = {
		id = "chen zhanglao",
		short = "chen",
		addr = {name = "空地", city = "丐帮"},
		skills = {
			-- ["huifeng-bian"] = {id = "huifeng-bian",level = 140,name = "回风鞭",},
			["suohou-shou"] = {id = "suohou-shou",level = 120,name = "锁喉擒拿手",},
			xiaoyaoyou = {id = "xiaoyaoyou",level = 140,name = "逍遥游",},
			parry = {id = "parry",level = 120,name = "基本招架",},
			dodge = {id = "dodge",level = 140,name = "基本轻功",},
			unarmed = {id = "unarmed",level = 120,name = "基本拳脚",},
			begging = {id = "begging",level = 110,name = "叫化绝活",},
			["huntian-qigong"] = {id = "huntian-qigong",level = 120,name = "混天气功",},
			force = {id = "force",level = 120,name = "基本内功",},
			hand = {id = "hand",level = 120,name = "基本手法",},
			whip = {id = "whip",level = 140,name = "基本鞭法",},
		}
	},
	["杨过"] = {
		id = "yang guo",
		addr = {name = "小室", city = "绝情谷"},
		skills = {
			cuff = {id = "cuff",level = 350,name = "基本拳法",},
			finger = {id = "finger",level = 140,name = "基本指法",},
			["jiuyin-zhengong"] = {id = "jiuyin-zhengong",level = 160,name = "九阴真功",},
			sword = {id = "sword",level = 350,name = "基本剑法",},
			["quanzhen-jianfa"] = {id = "quanzhen-jianfa",level = 360,name = "全真剑法",},
			medicine = {id = "medicine",level = 120,name = "本草术理",},
			["xuantie-jianfa"] = {id = "xuantie-jianfa",level = 370,name = "玄铁剑法",},
			dodge = {id = "dodge",level = 350,name = "基本轻功",},
			literate = {id = "literate",level = 250,name = "读书写字",},
			force = {id = "force",level = 350,name = "基本内功",},
			hand = {id = "hand",level = 350,name = "基本手法",},
			strike = {id = "strike",level = 350,name = "基本掌法",},
			["jingmai-xue"] = {id = "jingmai-xue",level = 80,name = "经脉学",},
			hamagong = {id = "hamagong",level = 300,name = "蛤蟆功",},
			parry = {id = "parry",level = 350,name = "基本招架",},
			["yunu-xinjing"] = {id = "yunu-xinjing",level = 350,name = "玉女心经",},
			["yunu-shenfa"] = {id = "yunu-shenfa",level = 350,name = "玉女身法",},
			["tianluo-diwang"] = {id = "tianluo-diwang",level = 340,name = "天罗地网式",},
			["xiantian-gong"] = {id = "xiantian-gong",level = 80,name = "先天功",},
			["anran-zhang"] = {id = "anran-zhang",level = 380,name = "黯然销魂掌",},
		}
	},
}